### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by ShafiqSadat** [Sammers21/tg-cleaner#1]
i cant build TDLIB
can you send me new TDlib bin files?
like : .dll and .so files need this source code!

**Comment by Sammers21** [comment]
The one i built on fedora 30(so might not work on other Linux distributions) is located inside the jar file: https://github.com/Sammers21/tg-cleaner/blob/master/lib/tdlib.jar

**Comment by Sammers21** [comment]
This file is attempted to be loaded if libtdjni.so not found in PATH

**Comment by Sammers21** [comment]
@ShafiqSadat , which OS you want to use to run tg-cleaner?

**Comment by Sammers21** [comment]
@ShafiqSadat , pay attention to the docker image i built. You can run tg-cleaner now with: 
```docker run -it sammers/tg-cleaner:1.0```

**Comment by Sammers21** [comment]
@ShafiqSadat , hey, any updates from you?
